// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/jackc/pgx/v5/pgxpool"
	"wenjuandiaocha_backend/internal/config"
	"wenjuandiaocha_backend/internal/dao"
	"wenjuandiaocha_backend/internal/server/http"
	"wenjuandiaocha_backend/internal/service/auth"
	"wenjuandiaocha_backend/internal/service/submission"
	"wenjuandiaocha_backend/internal/service/survey"
)

// Injectors from wire.go:

// InitServer 从连接池 + config 组装出 *http.Server。
// pool 的生命周期(创建/ping/close)由调用方(main)负责,不进 wire。
func InitServer(pool *pgxpool.Pool, cfg config.Config) *http.Server {
	store := dao.New(pool)
	manager := survey.New(store)
	submissionManager := submission.New(store)
	duration := provideSessionTTL(cfg)
	authManager := auth.New(store, duration)
	server := http.NewServer(manager, submissionManager, authManager, cfg)
	return server
}
