// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"wenjuandiaocha_backend/internal/config"
	"wenjuandiaocha_backend/internal/dao"
	"wenjuandiaocha_backend/internal/server/http"
	"wenjuandiaocha_backend/internal/service/auth"
	"wenjuandiaocha_backend/internal/service/submission"
	"wenjuandiaocha_backend/internal/service/survey"
)

// Injectors from wire.go:

// InitServer 组装整个依赖图:config(读环境)→ 连接池 → dao → 3 managers → *http.Server。
// 返回 cleanup(关连接池)与 error(config 缺项 / 连库失败),由 main 负责调用/退出。
func InitServer(ctx context.Context) (*http.Server, func(), error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, nil, err
	}
	store, cleanup, err := dao.New(ctx, configConfig)
	if err != nil {
		return nil, nil, err
	}
	manager := survey.New(store)
	submissionManager := submission.New(store)
	duration := provideSessionTTL(configConfig)
	authManager := auth.New(store, duration)
	server := http.NewServer(manager, submissionManager, authManager, configConfig)
	return server, func() {
		cleanup()
	}, nil
}
